sprint 13 v.1.0
ishimura2387/java-shareit pull request #1
Opened 2024-02-24 13:42 UTC by ishimura2387

2024-02-24 18:46 UTC, alexache requested changes

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @NotBlank
Аннотации валидации на "модели" скорее лишние, они имеют смысл на ДТО

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private int owner;
Тут желательно иметь User owner и ItemRequest request вместо чисел

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : items) {
(опционально) можно переделать на обработку в функциональном стиле с stream() .map()

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (!userStorage.findAllUsersId().contains(id)) {
Почему бы не сделать какой-то метод поиска по айди юзера?

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/MemoryItemStorage.java
> +        for (Item item : items.values()) {
(опционально) для более жффективного поиска вещей по владельцу можно завести дополнительную. мапу для хранения маппинга владельца на список его вещей

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/MemoryItemStorage.java
> +            if (item.getAvailable() && (item.getName().toLowerCase().contains(text.toLowerCase()) ||
text.toLowerCase() лучше вынести в переменную до цикла

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/MemoryUserStorage.java
> +        user.setId(counterUserId);
Не хватает сета имейлов, чтобы проверять их на отстутствие дубликатов

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    private void checkEmail(String email, int id) {
Это лучше проверять внутри стораджа с более эффективным алгоритмом, чем полный перебор списка

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (!userStorage.findAllUsersId().contains(id)) {
Довольно неэффективный способ с перебором списка

2024-02-24 18:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public class UserService {
Не хватает интерфейса UserService и реализации UserServiceImpl

2024-02-25 08:37 UTC, ishimura2387 commented on src/main/java/ru/practicum/shareit/user/MemoryUserStorage.java
> +        user.setId(counterUserId);
Вызов проверок осуществляется в сервисном слое т.к. при  использовании mapperStruct метода patch производится замена полей в бинах. Соответственно вызывать проверки нужно до замены, а вызов mapperStrcuct - точно слой сервиса. При работе с БД - доработаю и уйду от этой проблемы.

2024-02-25 08:42 UTC, ishimura2387 commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    private void checkEmail(String email, int id) {
При вызове проверки из стораджа возникают проблемы работы mapperStruct - он перезаписывает данные уже на этапе работы с DTO в слое сервиса. Исправлю в дальнейшем при работе с BD.

2024-02-26 06:52 UTC, alexache approved these changes

2024-02-26 06:52 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        item.setRequest(null); // видимо реалиация будет в следующих спринтах? в ТЗ ничего не сказано
Да, именно

2024-02-26 06:52 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            return new ArrayList<>();
(опционально) будет немного лучше использовать для таких случаев Collections.emptyList() чтобы не плодить мусор

2024-02-26 06:52 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (userStorage.getUser(id) == null) {
Когда будет база, будет лучше совместить checkUser с getUser чтобы не делать 2 запроса к базе на получение объекта юзера, то есть на примере Optional сделать .orElseThrow()

2024-02-26 06:52 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/MemoryItemStorage.java
> +    public void checkItemForService(int id) {
Пугающее название, из него не ясно, что вообще делает метод. Проще использовать Optional<Item> getItemById() и в сервисе при необходимости бросать исключение при отсутствии значения

2024-02-26 06:52 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/MemoryUserStorage.java
> +    private void checkEmail(String email, int id) { // вытащить в слой storage не получается как не пробовал,
Можно этот метод вызывать при создании/обновлении пользователя без пинка из сервиса. Не очень понимаю проблему.
А для эффективного происка имейлов можно завести отдельный хешсет

2024-02-26 06:52 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserServiceImpl userServiceImpl;
Это лишнее изменение. нельзя полагаться на реализацию, это идет в разрез с IoC. наверное авто-рефакторинг при создании интерфейса?

2024-03-03 01:08 UTC, merged

2024-03-03 04:52 UTC, ishimura2387 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (userStorage.getUser(id) == null) {
Реализовал отловом исключения EmptyResultDataAccessException